### ISSUE TITLE
Add support for list_link

### ISSUE THREAD

**Issue by igo** [gitaarik/django-admin-relation-links#14]
Please consider adding support for new link type which will show list of related objects, ie list of members of group:

```
class GroupAdmin(AdminChangeLinksMixin, admin.ModelAdmin):
    list_display = ['name', 'members']
    list_link = ['members']
```

Where `members` link would go to `/admin/app/member?group__id=...`.

**Comment by gitaarik** [comment]
I think this feature is already present, did you read the Readme?

**Comment by igo** [comment]
`changelist_links` displays link only in detail. I would like to have link in a list. Is this feature there? I didnt notice 🤨

**Comment by gitaarik** [comment]
it's even in the screenshots

**Comment by igo** [comment]
I see. How can I make it work? `changelist_links = ['members']` adds link only to detail page. It's not displayed in list page. Am I missing something?

**Comment by gitaarik** [comment]
https://github.com/gitaarik/django-admin-relation-links#list-page-links
