### ISSUE TITLE
Lookup filter is None when no related name is specified

### ISSUE THREAD

**Issue by beckstefan** [gitaarik/django-admin-relation-links#15]
When no `related_name` is specified in the `ForeignKeyField` the function `get_lookup_filter` returns `None` and the `lookup_filter` must be set manually.

When looking at

https://github.com/gitaarik/django-admin-relation-links/blob/1b096b2c5d8c0fbce73217e4fed18861a2773d7c/django_admin_relation_links/options.py#L27-L30

I think this could be replaced using `Options.get_field()`, since this covers `related_name` as well as the default value that is the model name.
https://docs.djangoproject.com/en/dev/ref/models/meta/#field-access-api

**Comment by gitaarik** [comment]
Hmm yeah looks like it, nice find :). Would you like to make a pull request?

**Comment by beckstefan** [comment]
Yes, I can definitely do that. Would you mind set up a small test system that I can use to verify it works properly?

**Comment by gitaarik** [comment]
Hey, thanks for the PR! I added a comment.

Yes I would like to add unit tests at some point, haven't had time to get that started yet.

**Comment by beckstefan** [comment]
I think you forgot to submit your comment, at least I can't any!

**Comment by gitaarik** [comment]
Strange, don't you see it in `README.md`  line `74` here?

https://github.com/gitaarik/django-admin-relation-links/pull/16/files

**Comment by gitaarik** [comment]
Oh I see now, I still had to finish and submit the review. I'm used to GitLab now, haven't used GitHub for these kinds of things in a while. Do you see it now?
