### ISSUE TITLE
Combine four statements into one

### ISSUE THREAD

**Issue by jaspercram** [gitaarik/django-admin-relation-links#19]
For most of my relations, I simply want both directions in the list page. To accomplish that, there are four places in the admin that I will have to change. 

``` python
@admin.register(Group)
class GroupAdmin(AdminChangeLinksMixin, admin.ModelAdmin):
    list_display = ['name', 'members_link']
    changelist_links = ['members']  

@admin.register(Member)
class MemberAdmin(AdminChangeLinksMixin, admin.ModelAdmin):
    list_display = ['name', 'group_link']
    change_links = ['group'] 
```

Would it be possible to introduce a shortcut to add all four at once. Something like

``` python
@admin.register(Group)
class GroupAdmin(admin.ModelAdmin):
    list_display = ['name']

@admin.register(Member)
class MemberAdmin(AdminChangeLinksMixin, admin.ModelAdmin):
    list_display = ['name']
    two_sided_relational_links_shortcut = ['group'] 
```
But then with beter naming....

**Comment by gitaarik** [comment]
I'm not sure if that would be something desired. I expect the settings 
of a particular admin page to be in the class of that page. It could 
result in weird bugs, and it will probably be hacky to make such an 
implementation anyway.

**Comment by jaspercram** [comment]
I see. Thanks for the feedback.
