### ISSUE TITLE
add count to the name of one-to-many links

### ISSUE THREAD

**Issue by jaspercram** [gitaarik/django-admin-relation-links#21]
The documentation describes how to add a count to the link name. This is super useful, but quite inefficient in a list view as it does a single query per row. Would it be possible to offer this feature in a way that it calculates all hundred counts in a single query?

**Comment by gitaarik** [comment]
I would not do this on the list page. If you want this functionality on the list page I would do it yourself, it's out of the scope of this project I would think.
