### ISSUE TITLE
NoReverseMatch when foreign key points to another app

### ISSUE THREAD

**Issue by ghost** [gitaarik/django-admin-relation-links#5]
When I use this for a ForeignKey pointing to a model in another Django app in the same project, I get a NoReverseMatch error. Is there any support for this use case?

**Comment by gitaarik** [comment]
Hi @dynamodeniz, no there isn't support for that. It shouldn't be too hard to create, I imagine you could do it by specifying the app with the `options` attribute, like:

    changelist_links = [
        ('member', {
            'label': 'All members',
            'app': 'other_django_app'
        })
    ]

Then you'll need use it on these places:
https://github.com/gitaarik/django-admin-relation-links/blob/master/django_admin_relation_links/options.py#L130
https://github.com/gitaarik/django-admin-relation-links/blob/master/django_admin_relation_links/options.py#L143

From the top of my head. Try it if you feel like it and make a pull request! :)

**Comment by gitaarik** [comment]
Hey, I actually just dived into it myself and it should work now ;) I just released 0.1.0, can you check it? Note: for the changelist links you should now specify the `related_name`, not the model name of the related model.

**Comment by ghost** [comment]
Works good now! I think you accidentally broke Django 2.0 support though, I had to change this line:

    from django.core.urlresolvers import reverse

to

    from django.urls import reverse

:) Thank you!

**Comment by gitaarik** [comment]
Ah, funny that got back in, thanks! Fixed it, you can now use `0.1.1`
