### ISSUE TITLE
License to MIT?

### ISSUE THREAD

**Issue by tony** [gitaarik/django-admin-relation-links#7]
Hi!

Is it possible to switch the license on this to MIT/BSD/etc. by any chance?

I'd like to use this package, but would rather write my own than introduce
complications from LGPL / python.  The reason why is the license isn't
written with scripting languages in mind. The other reason is as it's a django package I think
it makes more sense to keep it under the same license django uses.

Similar issue where I brought up specifics I dealt with Python / LGPL: https://github.com/pytest-dev/pytest-mock/issues/45

P.S. I'm not against (L)GPL in any way, there are just developers that can't
pull in projects that have licenses with viral clauses.

**Comment by gitaarik** [comment]
Hey, I'll think about it this week

**Comment by tony** [comment]
At this point I've already whipped something up internally that does what this project does. So my particular case isn't as strong as when I originally posted.

But since this is a Django package, if it's part of that ecosystem, I think whatever license is typical there is probably a better fit?
